# Currency schema

# --- !Ups

CREATE TABLE CURRENCY (
  ID BIGINT PRIMARY KEY,
  CODE CHAR(3) NOT NULL,
  NAME VARCHAR(48) NOT NULL
);

INSERT INTO CURRENCY VALUES (643, 'RUB', '₽');
INSERT INTO CURRENCY VALUES (203, 'CZK', 'Czech Koruna');
INSERT INTO CURRENCY VALUES (840, 'USD', '$');
INSERT INTO CURRENCY VALUES (978, 'EUR', '€');

# --- !Downs
DROP TABLE CURRENCY;