# Transaction schema

# --- !Ups

CREATE TABLE TAG (
  ID BIGSERIAL PRIMARY KEY,
  TAG TEXT NOT NULL UNIQUE
);

CREATE TABLE TX (
  ID BIGSERIAL PRIMARY KEY,
  TS TIMESTAMP NOT NULL DEFAULT NOW(),
  COMMENT TEXT
);

CREATE TABLE TX_TAGS (
  TAG_ID BIGINT NOT NULL REFERENCES TAG(ID) ON DELETE RESTRICT,
  TX_ID BIGINT NOT NULL REFERENCES TX(ID) ON DELETE CASCADE,
  PRIMARY KEY (TAG_ID, TX_ID)
);

CREATE TABLE OPERATION (
  ID BIGSERIAL PRIMARY KEY,
  TX_ID BIGINT NOT NULL REFERENCES TX(ID) ON DELETE CASCADE,
  ACCOUNT_ID BIGINT NOT NULL REFERENCES ACCOUNT(ID) ON DELETE RESTRICT,
  AMOUNT DECIMAL(32,2) NOT NULL DEFAULT 0
);

CREATE OR REPLACE FUNCTION account_op_add() RETURNS TRIGGER
  AS $account_op_add$
  DECLARE
    CURRENT DECIMAL(32,2);
  BEGIN
    SELECT balance INTO current FROM account WHERE id = NEW.ACCOUNT_ID;
    UPDATE account SET balance = current + NEW.AMOUNT WHERE id = NEW.ACCOUNT_ID;
    RETURN NEW;
END;
$account_op_add$ LANGUAGE plpgsql;

CREATE TRIGGER op_add AFTER INSERT ON operation FOR EACH ROW EXECUTE PROCEDURE account_op_add();

CREATE OR REPLACE FUNCTION account_op_del() RETURNS TRIGGER
AS $account_op_del$
DECLARE
  CURRENT DECIMAL(32,2);
BEGIN
  SELECT balance INTO current FROM account WHERE id = OLD.ACCOUNT_ID;
  UPDATE account SET balance = current + -1 * OLD.AMOUNT WHERE id = OLD.ACCOUNT_ID;
  RETURN OLD;
END;
$account_op_del$ LANGUAGE plpgsql;

CREATE TRIGGER op_del BEFORE DELETE ON operation FOR EACH ROW EXECUTE PROCEDURE account_op_del();

CREATE OR REPLACE FUNCTION account_op_upd() RETURNS TRIGGER
AS $account_op_upd$
BEGIN
  RAISE EXCEPTION 'Operations can not be updated';
END;
$account_op_upd$ LANGUAGE plpgsql;

CREATE TRIGGER op_upd BEFORE UPDATE ON operation FOR EACH ROW EXECUTE PROCEDURE account_op_upd();

INSERT INTO ERROR VALUES('TRANSACTION_NOT_FOUND', '404', 'Requested transaction could not be found', 'We can not find transaction with specified code in the database, check it''s id please.');
# --- !Downs
DELETE FROM ERROR WHERE CODE = 'TRANSACTION_NOT_FOUND';

DROP TRIGGER op_upd ON operation;
DROP TRIGGER op_del ON operation;
DROP TRIGGER op_add ON operation;
DROP FUNCTION account_op_upd();
DROP FUNCTION account_op_del();
DROP FUNCTION account_op_add();
DROP TABLE OPERATION;
DROP TABLE TX_TAGS;
DROP TABLE TX;
DROP TABLE TAG;
