dist: trusty
sudo: required
language: scala
scala: 
  - 2.11.8
addons:
  postgresql: "9.2"
services:
  - postgresql
  - docker
before_script:
  - psql -f docs/createdb.sql -U postgres
  - git clone https://github.com/akashihi/mdg-api-test
script:
  # Build it
  - sbt universal:packageZipTarball
  - cd target/universal
  - tar zxvf mdg.tgz
  - cd mdg  
  # Run the server
  - |    
    ./bin/mdg -Dplay.crypto.secret=test &
    SERVER_PID=$!
  - echo Mdg server is running with $SERVER_PID pid.
  # Give mdg some time to settle
  - sleep 10
  # Execute test suite
  - cd ../../../
  - cd mdg-api-test
  - gradle test
after_script:
  # Stop server
  - kill $SERVER_PID  
before_deploy:
  - cd ../
  - cp target/universal/mdg.tgz docker/
  - cd docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_build.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_TAG
  on:
    all_branches: true

