dist: trusty
sudo: required
language: scala
scala:
- 2.12.1
addons:
  postgresql: '9.2'
services:
- postgresql
- docker
- elasticsearch
before_script:
- sleep 10 # Elasticsearch needs some time for start-up
- psql -f docs/createdb.sql -U postgres
- git clone https://github.com/akashihi/mdg-api-test
script:
- sbt universal:packageZipTarball
- cd target/universal
- tar zxvf mdg.tgz
- cd mdg
- |
  ./bin/mdg -Dplay.crypto.secret=test &
  SERVER_PID=$!
- echo Mdg server is running with $SERVER_PID pid.
- sleep 10
- cd ../../../
- cd mdg-api-test
- gradle test
after_script:
- kill $SERVER_PID
before_deploy:
- cd ../
- cp target/universal/mdg.tgz docker/
- cd docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_build.sh $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_TAG
  on:
    all_branches: true
env:
  global:
    - DOCKER_USERNAME=akashihi
    - secure: aNgT029hjgCeaxOcC8g731w7jiBLll4A/fQCcFAcdKmkUi1Ugazin8DDVNxt9tR4Qx6wjeDuxWGy/pFCIasRVLwcaxDkNzVf3wIQHvuIZ5r2b1IdwFarf7A23dkmRp30+xiTgZQDoNUjnv/HG3YFLj196EsEuo+ozg1++ykQLVxI/5qTeGPwfMY8PwFCmWSB35bAzq7oVsKv3eKqSoXE6YZ3kpbN5bS2DcQoRkeMiraHQHMojwDIdDd68sFoK2Ngra+lbZLkNrEsPNxMpmZWZ0N7GYJAzl7V4ZTOWL8k20hQqr0DA1LVlGGMp1erBYd4PvYIzKen1nw8QOPyFJ1uZO3tMKKJ5ijuCkQLP8XjWgKiKS6apWpUKGdH3dUmvDZbn+iiZ2z0Tbh0Q8480UORrRgqyuHeOkVllPSgRUeupnVvkRYhQU3/TpjPN3WEP3DeEcKFBVIushi89PIrhYNe3J2V0C9WCSB1QhqAsZdSMoD0j5r4Z3giAzJdjNDpkoHQqvUbXS/IcRoK0XwIINtJTAMIBWydPtz4cTIzVkXB5MKBsps7+HqBfsBYVR2GltiO6Z1YcW075PS7u6O2c//FRls5dwQDEcmZykQcmnc2SHGicsa4OHOMIX+9K1LfRZ3m2iy1Wql2gCMZbkqBPwY9cJk3e8mDWjSCh4k/f8eLdW0=
