--liquibase formatted sql

--changeset akashihi:1
CREATE TABLE CATEGORY(
    ID BIGSERIAL PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR(7) NOT NULL CHECK(ACCOUNT_TYPE IN ('asset', 'expense', 'income')),
    NAME TEXT NOT NULL,
    PRIORITY INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE CATEGORY_TREE (
    ANCESTOR BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
    DESCENDANT BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE CASCADE,
    DEPTH INTEGER NOT NULL
);

ALTER TABLE ACCOUNT ADD COLUMN CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY(ID) ON DELETE RESTRICT;

--rollback DROP TABLE CATEGORY;
--rollback DROP TABLE CATEGORY_TREE;
--rollback ALTER TABLE ACCOUNT DROP COLUMN CATEGORY_ID;
