--liquibase formatted sql

--changeset akashihi:1

ALTER TABLE ACCOUNT ADD COLUMN OPERATIONAL BOOLEAN NOT NULL DEFAULT 'f';
ALTER TABLE ACCOUNT ADD COLUMN FAVORITE BOOLEAN NOT NULL DEFAULT 'f';

--rollback ALTER TABLE ACCOUNT DROP COLUMN OPERATIONAL;
--rollback ALTER TABLE ACCOUNT DROP COLUMN FAVORITE;
