--liquibase formatted sql

--changeset akashihi:1
CREATE TABLE RATE (
  ID BIGSERIAL PRIMARY KEY,
  RATE_BEGINNING TIMESTAMP NOT NULL,
  RATE_END TIMESTAMP NOT NULL,
  FROM_ID BIGINT NOT NULL REFERENCES CURRENCY(ID),
  TO_ID BIGINT NOT NULL REFERENCES CURRENCY(ID),
  RATE DECIMAL(32,2) NOT NULL DEFAULT 0
);

INSERT INTO RATE(RATE_BEGINNING, RATE_END, FROM_ID, TO_ID, RATE) VALUES ('0001-01-01 00:00:00', '9999-12-31 23:59:59', 978, 840, 1.19);

--rollback DROP TABLE RATE;

--changeset akashihi:2
ALTER TABLE RATE RENAME TO RATES;

--rollback ALTER TABLE RATES RENAME TO RATE;
