--liquibase formatted sql

--changeset akashihi:1
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Cash', 1);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Current', 2);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Savings', 3);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Deposit', 4);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Credit', 5);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Debt', 6);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Broker', 7);
INSERT INTO CATEGORY (ACCOUNT_TYPE, NAME, PRIORITY) VALUES ('asset', 'Tradable', 8);

--rollback DELETE FROM CATEGORY WHERE ACCOUNT_TYPE = 'asset';

--changeset akashihi:2
UPDATE ACCOUNT AS A SET CATEGORY_ID = (SELECT C.ID FROM CATEGORY AS C, ASSET_ACCOUNT_PROPERTIES AS AA WHERE LOWER(C.NAME) = AA.ASSET_TYPE AND AA.ID=A.ID) WHERE A.ACCOUNT_TYPE='asset';

--rollback UPDATE ACCOUNT SET CATEGORY_ID=NULL WHERE ACCOUNT_TYPE = 'ASSET';

--changeset akashihi:3
ALTER TABLE ASSET_ACCOUNT_PROPERTIES DROP COLUMN ASSET_TYPE;