--liquibase formatted sql

--changeset akashihi:1
ALTER TABLE BUDGETENTRY ADD COLUMN DISTRIBUTION VARCHAR(8);
UPDATE BUDGETENTRY SET DISTRIBUTION=CASE WHEN even_distribution AND proration THEN 'PRORATED' WHEN even_distribution AND NOT proration THEN 'EVEN' ELSE 'SINGLE' END;
alter table BUDGETENTRY alter column DISTRIBUTION set not null;
ALTER TABLE BUDGETENTRY DROP COLUMN proration;
ALTER TABLE BUDGETENTRY DROP COLUMN even_distribution;

--rollback ALTER TABLE BUDGETENTRY ADD COLUMN even_distribution BOOLEAN NOT NULL DEFAULT TRUE;
--rollback ALTER TABLE BUDGETENTRY ADD COLUMN proration BOOLEAN NOT NULL DEFAULT TRUE;
--rollback UPDATE BUDGETENTRY SET proration=FALSE where DISTRIBUTION='EVEN';
--rollback UPDATE BUDGETENTRY SET proration=FALSE, even_distribution=FALSE where DISTRIBUTION='SINGLE';
--rollback ALTER TABLE BUDGETENTRY DROP COLUMN DISTRIBUTION;
