--liquibase formatted sql

--changeset akashihi:1
ALTER TABLE BUDGETENTRY ALTER COLUMN DISTRIBUTION SET DEFAULT 'PRORATED';

--rollback ALTER TABLE BUDGETENTRY ALTER COLUMN DISTRIBUTION DROP DEFAULT;
