export const GET_BUDGETREPORT_REQUEST = 'GET_BUDGETREPORT_REQUEST'
export const GET_BUDGETREPORT_SUCCESS = 'GET_BUDGETREPORT_SUCCESS'
export const GET_BUDGETREPORT_FAILURE = 'GET_BUDGETREPORT_FAILURE'

export const GET_EXPENSEEVENTACCOUNTREPORT_REQUEST = 'GET_EXPENSEEVENTACCOUNTREPORT_REQUEST'
export const GET_EXPENSEEVENTACCOUNTREPORT_SUCCESS = 'GET_EXPENSEEVENTACCOUNTREPORT_SUCCESS'
export const GET_EXPENSEEVENTACCOUNTREPORT_FAILURE = 'GET_EXPENSEEVENTACCOUNTREPORT_FAILURE'

export const GET_EXPENSEWEIGHTACCOUNTREPORT_REQUEST = 'GET_EXPENSEWEIGHTACCOUNTREPORT_REQUEST'
export const GET_EXPENSEWEIGHTACCOUNTREPORT_SUCCESS = 'GET_EXPENSEWEIGHTACCOUNTREPORT_SUCCESS'
export const GET_EXPENSEWEIGHTACCOUNTREPORT_FAILURE = 'GET_EXPENSEWEIGHTACCOUNTREPORT_FAILURE'

export enum ReportActionType {
    TotalsReportLoad = 'TotalsReportLoad',
    TotalsReportStore = 'TotalsReportStore'
}
