export const GET_BUDGETREPORT_REQUEST = 'GET_BUDGETREPORT_REQUEST'
export const GET_BUDGETREPORT_SUCCESS = 'GET_BUDGETREPORT_SUCCESS'
export const GET_BUDGETREPORT_FAILURE = 'GET_BUDGETREPORT_FAILURE'

export const GET_CURRENCYASSETREPORT_REQUEST = 'GET_CURRENCYASSETREPORT_REQUEST'
export const GET_CURRENCYASSETREPORT_SUCCESS = 'GET_CURRENCYASSETREPORT_SUCCESS'
export const GET_CURRENCYASSETREPORT_FAILURE = 'GET_CURRENCYASSETREPORT_FAILURE'

export const GET_TYPEASSETREPORT_REQUEST = 'GET_TYPEASSETREPORT_REQUEST'
export const GET_TYPEASSETREPORT_SUCCESS = 'GET_TYPEASSETREPORT_SUCCESS'
export const GET_TYPEASSETREPORT_FAILURE = 'GET_TYPEASSETREPORT_FAILURE'

export const GET_INCOMEEVENTACCOUNTREPORT_REQUEST = 'GET_INCOMEEVENTACCOUNTREPORT_REQUEST'
export const GET_INCOMEEVENTACCOUNTREPORT_SUCCESS = 'GET_INCOMEEVENTACCOUNTREPORT_SUCCESS'
export const GET_INCOMEEVENTACCOUNTREPORT_FAILURE = 'GET_INCOMEEVENTACCOUNTREPORT_FAILURE'

export const GET_EXPENSEEVENTACCOUNTREPORT_REQUEST = 'GET_EXPENSEEVENTACCOUNTREPORT_REQUEST'
export const GET_EXPENSEEVENTACCOUNTREPORT_SUCCESS = 'GET_EXPENSEEVENTACCOUNTREPORT_SUCCESS'
export const GET_EXPENSEEVENTACCOUNTREPORT_FAILURE = 'GET_EXPENSEEVENTACCOUNTREPORT_FAILURE'

export const GET_INCOMEWEIGHTACCOUNTREPORT_REQUEST = 'GET_INCOMEWEIGHTACCOUNTREPORT_REQUEST'
export const GET_INCOMEWEIGHTACCOUNTREPORT_SUCCESS = 'GET_INCOMEWEIGHTACCOUNTREPORT_SUCCESS'
export const GET_INCOMEWEIGHTACCOUNTREPORT_FAILURE = 'GET_INCOMEWEIGHTACCOUNTREPORT_FAILURE'

export const GET_EXPENSEWEIGHTACCOUNTREPORT_REQUEST = 'GET_EXPENSEWEIGHTACCOUNTREPORT_REQUEST'
export const GET_EXPENSEWEIGHTACCOUNTREPORT_SUCCESS = 'GET_EXPENSEWEIGHTACCOUNTREPORT_SUCCESS'
export const GET_EXPENSEWEIGHTACCOUNTREPORT_FAILURE = 'GET_EXPENSEWEIGHTACCOUNTREPORT_FAILURE'

export enum ReportActionType {
    TotalsReportLoad = 'TotalsReportLoad',
    TotalsReportStore = 'TotalsReportStore'
}
