FORMAT: 1A
HOST: https://localhost/api

# MDG

MDG is a self-hosted personal accounting web service.

This API document is available at https://mdg1.docs.apiary.io/ and describes API v1

# Group Settings

Resources describing system configuration variables.

## Setting [/settings/{id}]

+ parameters
    + id (required, string) - Name of the setting
        Valid setting names are:

        * currency.primary - Changes primary currency of the MDG. Value is a currency id
        * ui.transaction.closedialog - Configures auto-closing of transaction dialog, values are "true" or "false"
        * ui.language - Configures sytem locale. At the moment it only has impact on full-text indexing settings. Valid values are locale names like "en-US".
        * mnt.transaction.reindex - Triggers transaction reindexing. This setting can only be written.

+ Attributes (object)
    + id: currency.primary (string, required) - Seting name
    + value: 978 (string, required) - Setting value as a string. As different settings may have different meaning, they values are transferred as strings.

### View a Setting [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Setting)
+ Response 404 (application/vnd.mdg+json;version=1)
    + Attributes (Problem)
+ Response 422 (application/vnd.mdg+json;version=1)
    + Attributes (Problem)

### Modify setting value [PUT]

Settings may have different valid values for different names. Invalid values will not be accepted

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Setting)

+ Response 202 (application/vnd.mdg+json)
    + Attributes (Setting)
## Settings Collection [/settings]

### List All Settings [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + settings (array[Setting], required) - Array of settings

# Group Currencies

Resources describing currencies known to the system.
Currencies are identified by their numeric ISO 4217 code

## Currency [/currencies/{id}]

+ parameters
    + id (required, number) - ID of a currency in form of ISO 4217 number-3 code

+ Attributes (object)
    + id: 978 (string, required) - Currency ISO 4217 alfa-3 code
    + code: EUR (string, required) - Short currency code
    + name: € (string, required) - Human friendly currency name
    + active: true (boolean, required) - Whether this currency is used or not
        Inactive currencies are known by the system, but do not participate in other activities, like rate retireval account management etc


### View a currency detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Currency)
+ Response 404 (application/vnd.mdg+json;version=1)
    + Attributes (Problem)


### Modify currency data [PUT]

Only `active` field could be changed. Values in the other fields will be silently ignored.

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Currency)

+ Response 202 (application/vnd.mdg+json)
    + Attributes (Currency)

## Currencies [/currencies]

### List All Currencies [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + currencies (array[Currency], required) - Array of currencies

# Group Rates

Resources describing currency exchange rates

## Rate [/rates/{timestamp}/{from}/{to}]

+ parameters
    + timestamp: `YYYY-MM-DDTHH:MM:SS (string, required) - Point in time in format YYYY-MM-DDTHH:MM:SS for which exchange rates should be valid
    + from: 978 (number, required) - ID of a "sell" currency in form of ISO 4217 number-3 code
    + to: 840 (number, required) - ID of a "buy" currency in form of ISO 4217 number-3 code

+ Attributes
    + id: 1 (number, required) - Syntetic id value
    + from: 978 (string, required) - "Sell" currency ISO 4217 number-3 code
    + to: 840 (string, required) - "Buy" currency ISO 4217 number-3 code
    + rate: 1.19 (number, required) - Exchange rate, telling you how much 'from' currency should be spent, to by a single 'to' currency unit
    + beginning: `YYYY-MM-DDTHH:MM:SS` (string, required) - Timestamp of the rate validity period beginning
    + end: `YYYY-MM-DDTHH:MM:SS` (string, required) - Timestamp of the rate validity period end

### View a rate detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Rate)

## Rate collection [/rates/{timestamp}]

+ parameters
    + timestamp: `YYYY-MM-DDTHH:MM:SS` (string, required) - Point in time for which exchange rates should be valid

### List All Rates [GET]

+ Response 200  (application/vnd.mdg+json;version=1)
    + Attributes
        + rates (array[Rate], required) - Array of rates for the specified point in time

## Rate Status [/rates/status]

+ Attributes
    + ts: `YYYY-MM-DDTHH:MM:SS` (string, required) - Last successful rate update timestamp

### View rate update status [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Rate Status)

# Group Categories

Resources describing account categories. A category is just an account label, used in analysis, statistics, rendering etc.

## Category [/categories/{category_id}]

+ parameters
    + category_id (number, required) - ID of a category

+ Attributes
    + id: 2 (number, required) - Due to hierarchical nature of categories, category is an exception and provides id twice: inside of a attributes and in a wrapper object.
    + parent_id: 1 (number, optional) - Category's parent category id. May be missing for top level categories
    + name: "Pet expenses" (string, required) - Category name
    + priority: 7 (number, required) - Ordering weight of that category. Categories output will be sorted ascendant by that weight. Same rule applies to the chidlren attribute.
    + account_type: "EXPENSE" (enum, required) - Type of the accounts suitable for that category. Can only be set during category creation. Category may only have children of same category.
        + `ASSET`
        + `EXPENSE`
        + `INCOME`
    + children (array[Category], optional) - Array of subcategories of that categories, may be empty or missing.

### View a category detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Category)


### Modify category data [PUT]

Only `parent_id`, `name` and `priority` fields could be changed. Values in other fields will be silently ignored. Changing 'parent_id' gives that category a new place in a category tree. all chidlren categories of that categories will be moved with their ancsetor. In case new parent is a descendand of that category, error will be returned. Set parent_id to the category id (self) to make that category a top level category. Parenting category to the parent with different account_type is not possible.

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Category)

+ Response 202 (application/vnd.mdg+json;version=1)
    + Attributes (Category)

### Delete a category [DELETE]

Deleting a category reparents all it's 1st degree descendants to the up level parent or makea them top-level categories, if no up-level parent is available. Linked accounts will be uncategorized.

+ Response 204

## Category collection [/category]

### List all Categories [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + categories (array[Category], required) - Array of categories

### Create a new category [POST]

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Category)

+ Response 201 (application/vnd.mdg+json)
    + Headers

            Location: /category/5

    + Attributes (Category)

# Group Accounts

Resources related to account management

## Account [/accounts/{account_id}?embed={embed}]

+ parameters
    + account_id: 2 (number, required) - ID of an account in form of integer
    + embed: currency,category (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

+ Attributes
    + id: 2 (number, required) - Account id
    + account_type: 'ASSET' (enum[string], required) - type of the account
      + Members
        + `ASSET`
        + `EXPENSE`
        + `INCOME`
    + currency_id: 978 (number, required) - account's currency id
    + currency (Currency, optional) - account's associated currency object.
    + category_id: 1 (number, optional) - account's category id, may be missing in case account doesn't belongs to the any category.
    + category (Category, optional) - account's associated category object.
    + name: 'wallet' (string, required) - Account name
    + balance: 3.62 (number, required) - Account balance, read only attribute.
    + primary_balance: 2.98 (number, required) - Account balance in primary currency, read only attribute. Automatically converted from the 'balance' field by applying correspondent rate.
    + hidden: false (boolean, optional) - Marks deleted accounts
    + operational: true (boolean, required) - Whether asset account is marked boolean. Valid for asset accounts only.
    + favorite: true (boolean, required) - Whether asset account is marked favorite. Valid for asset accounts only.

### View an account detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Account)

### Modify account data [PUT]

Only `hidden`, `name`, `category_id`, `favorite` and `operational` fields could be changed. Values in other fields will be silently ignored.

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Account)

+ Response 202 (application/vnd.mdg+json;version=1)
    + Attributes (Account)


### Delete an account [DELETE]

Only accounts without operations will be deleted. If there exists any operations, referring to the account, an error will be returned instead. Check the `status` object below.

+ Response 204

## Account collection [/accounts?q={query}&embed={embed}]

+ Parameters
    + query (object, optional) - dictionary of fields and their values, to be applied as a filter to accounts list.
    + embed: currency,category (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

### List all Accounts [GET]

Accounts with attribute 'hidden' equal to 'true' are shown if no filter is specified.

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + accounts (array[Account], required) - Array of accounts (flat)

### Create a new account [POST]

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Account)

+ Response 201 (application/vnd.mdg+json;version=1)
    + Attributes (Account)


## Account tree [/accounts/tree?q={query}&embed={embed}]

+ Parameters
    + query (object, optional) - dictionary of fields and their values, to be applied as a filter to accounts list.
    + embed: [currency,category] (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

### Get all Accounts [GET]

Accounts with attribute 'hidden' equal to 'true' are shown if no filter is specified. Categories may include transient categories, like 'Favorite' with **negative** ids.

+ Response 200 (application/vnd.mdg+json;version=1)

        {
            "asset": {
                "accounts": [
                    {
                        "id": 2,
                        "account_type": "ASSET",
                        "currency_id": 978,
                        "name": "wallet",
                        "balance": 3.62,
                        "primary_balance": 2.98,
                        "hidden": false,
                        "favorite": false,
                        "operational": false
                    }
                ],
                "categories": [
                    {
                        "id": 2,
                        "name": "cash",
                        "accounts": [
                            {
                                "id": 3,
                                "account_type": "ASSET",
                                "currency_id": 978,
                                "name": "wallet",
                                "balance": 3.62,
                                "primary_balance": 2.98,
                                "hidden": false,
                                "favorite": false,
                                "operational": false
                            }
                        ],
                        "categories": {
                            "accounts": [],
                            "categories": []
                        }
                    }
            ]
        }

## Account status [/accounts/{account_id}/status]

+ parameters
    + account_id: 2 (number, required) - ID of an account in form of integer

+ Attributes
    + id: 2 (number, required) - Account id
    + deletable: false (boolean, required) - Whether account could be deleted or not.

### Retrieve account status [GET]

+ Response 201 (application/vnd.mdg+json;version=1)
    + Attributes (Account status)

# Group Tags

Transaction tags dictionary. Each tag is an unique, case-insensitive string.

## Tag [/tags]

Tags are managed using a transaction. It is only possible to view list of tags, but not modify, neither remove them

### List all Tags [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + tags (array[string], required) - All tags used in the MDG

# Group Transactions

Resources related to Transaction management

## Transaction [/transactions/{transaction_id}?embed={embed}]

Transaction object have some limitations:
  - Operations with amount equal to zero are ignored
  - It should include at least on non-zero operation
  - Sum of all operations must be zero (excluding ignored operations)
  - Rate value may not be present only on accounts with same currency and only for one currency. So, if you have operations only on accounts with 'EUR' currency, 'rate' field can be omited. If you have several operations on 'EUR' accounts and 'USD' accounts, 'rate' field can be omited for all 'EUR' accounts or 'USD' accounts, but not for both.
  - Same applies in opposite direction - in a multicurrency transaction operations on some curency rate must not be specified or specified it as 1.
  - Rate may not be zero.
  - Rate values may differ in each operation with exclusion: if some operation have no 'rate' field set or rate set to '1', all other operations on accounts with same currency must have same rate of 1 or no rate. You can mix operations with rate equal to 1 and operations with no rate on same currency.

Multi currency support is implemented by checking, that all operations or all operations, excluding operations for some single currency, have a rate field. During transaction balance validation, amount of the
operation will be multiplied to its rate and only after that it will be summarized. It is recommended to always fill 'rate' field, setting its value to 1 where currency conversion is not required, so currency operations with rate '1' will be used as base currency. It is also recommended to use system's default currency as a conversion base.

+ parameters
    + transaction_id (required, number) - ID of a transaction in form of integer
    + embed: currency,category,account (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

+ Attributes
    - timestamp: `YYYY-MM-DDTHH:MM:SS` (string, required) - transaction timestamp
    - comment: 'Salary payment' (string, optional) - transaction description
    - tags: 'income','salary' (array[string], optional) - tags, associated with transaction
    - operations (array[Operation], required) - Each operation has the following attributes

### View a transaction detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Transaction)

### Modify transaction data [PUT]

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Transaction)

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Transaction)


### Delete an transaction [DELETE]

+ Response 204

## Transaction collection [/transactions?q={q}&sort={sort}&embed={embed}&limit={limit}&cursor={cursor}]

### List all Transactions [GET]

+ Parameters
  + q (object, optional) - dictionary of fields and their values, to be applied as a filter to transactions list. For attributes of array type it could also be an array. Filtering could be done only on `comment`, `tags` and `account_id` attributes. Timestmap filtering is supported with 'notEarlier' and 'notLater' keys
  + sort: timestamp (array[string], optional) - list of fields used for transactions list sorting. Sort will be applied in the same order as fields are listed. Prepend field name with dash, to revert sort order.
  + embed: account,currency,category (array[string], optional) - Objects to embed. accout_id and other _id fields are always provided.
  + limit: 10 (number, optional) - Paginate list using specified page size.
  + cursor: AAABBB (string, optional) - A pointer to the next page. Only valid if cursor value was previously set by the backend.
    The `cursor` field is used in the cursor based paging. In case `limit` is set, a single page holding a `limit`
    number of trasactions will be returned along side with additional cursor fields (see below). Each cursor is
    self-contained and can be used without repeating other parameters.

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + transactions (array[Transaction], required) - Transactions covered by the request
        + self: AAABBB (string, optional) - Cursor of the current page.
        + first: AAABBB (string, optional) - Cursor of the first page
        + next: AAABBB (string, optional) - Cursor of the following page
        + left: 15 (number,optional) - Number of items left after the current page.


### Create a new transaction [POST]

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Transaction)

+ Response 202 (application/vnd.mdg+json;version=1)
    + Attributes (Transaction)

# Group Budget

Resources related to budget management

## Budget [/budgets/{YYYY}{MM}{DD}]

+ parameters
    + YYYY: `2022` (required, number) - Budget's year
    + MM: `03` (required, number) - Budget's month
    + DD: `28` (required, number) - Budget's day. A budget with closest `term_beginning` before or equal to specified date will be retrieved

+ Attributes
    + term_beginning: `YYYY-MM-DD` (string, required) - Budget is not effective before specified point in time
    + term_end: `YYYY-MM-DD` (string, required) - Budget is not effective after specified point in time. Minimum Budget effectivity period is a day (24 hours).
    + incoming_amount: 8000 (number, required, readonly) - Sum of all amounts on accounts with account_type 'asset'. Value is not fixed and subject to change until term_beginning comes. It will be automatically filled. Exposed in primary currency.
    + outgoing_amount: 9000 (BudgetPair, required, readonly) - for expected: Estimated sum of all amounts on accounts with account_type 'asset' *after* budget completion. Value is calculated automatically when related BudgetEntries are added/removed/modified. Exposed in primary currency. For actual: Sum of all amounts on accounts with account_type 'asset' *after* budget completion. Calculated during budget execution. Exposed in primary currency.
    + state
      + income (BudgetPair, required) - For expected: Income expected to be received during budget validity period. Calculated as a sum of expected values on budget entries related to income accounts. Exposed in primary currency. For actual: Actual income, received during budget validity period. Calculated as a sum of income account operations, happened during transaction validity period. Exposed in primary currency.
      + expense (BudgetPair, required) - For expected: Expected expenses during budget validity period. Calculated as a sum of expected values on budget entries related to expense accounts. Exposed in primary currency. For actual: Actual expenses, happened during budget validity period. Calculated as a sum of expense account operations, happened during transaction validity period. Exposed in primary currency.
      + change (BudgetPair, required) - For expected: Expected change on expense accounts amounts for today. Calculated as a sum of change values on budget entries related to expense accounts. For non-current account will be zero. Exposed in primary currency. For actual: Actual change on expense accounts amounts, happened today. Calculated as a sum of expense account operations, happened today. For non-current account will be zero. Exposed in primary currency.

### View Budget detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (Budget)

### Delete a Budget [DELETE]

+ Response 204

## Budget collection [/budget?limit={limit}&cursor={cursor}]

  + limit: 10 (number, optional) - Paginate list using specified page size.
  + cursor: AAABBB (string, optional) - A pointer to the next page. Only valid if cursor value was previously set by the backend.
    The `cursor` field is used in the cursor based paging. In case `limit` is set, a single page holding a `limit`
    number of budgets will be returned along side with additional cursor fields (see below). Each cursor is
    self-contained and can be used without repeating other parameters.

Only term_beginning and term_end are returned for a budget collection. Detailed info (incoming_amount, outgoing_amount, state) can be retrieved by reading specific budget object.

### Create a new budget [POST]

Budgets effective dates are inclusive and should not overlap.

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (Budget)

+ Response 202 (application/vnd.mdg+json;version=1)
    + Attributes (Budget)


### List all Budgets [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + budgets (array[Budget], required) - Transactions covered by the request
        + self: AAABBB (string, optional) - Cursor of the current page.
        + first: AAABBB (string, optional) - Cursor of the first page
        + next: AAABBB (string, optional) - Cursor of the following page
        + left: 15 (number,optional) - Number of items left after the current page.

## BudgetEntry [/budgets/{budget_id}/entries/{entry_id}&embed={embed}]

BudgetEntry lifecycle is managed automatically. It will be created with budget and deleted with budget. During creation of new non-"asset" account, corresponding budget entries should be automatically provided to all existing budgets.

+ parameters
    + budget_id: YYYYMMDD (string, required) - ID of owning budget in form of integer
    + entry_id: 1 (number, required) - ID of a entry in form of integer
    + embed: currency,category,account (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

+ Attributes
    + account_id: 1 (number, required) - id of account, linked to that BudgetEntry. Every account could be used only once per each Budget.
    + account (Account, optional) - Related account information.
    + category_id: 1 (number, optional) - Related account's category id, may be missing in case account doesn't belongs to the any category.
    + category (Category, optional) - Related account's associated category object.
    + dt: `YYYY-MM-DD` (string, optional) - Estimated payment date. Only valid for entries with mode 'SINGLE'. For missing values in 'SINGLE' mode entries the first day of budget is assumed as a payment date.
    + distribution: 'SINGLE' (BudgetEntryMode, required) - Cashflow/Spending estimation mode for the buget
    + expected_amount: 1000 (number, required) - your expected change on account_id amount during Budget effective period.
    + actual_amount: 50 (number, required) - your *actual* change on account_id amount during Budget effective period. Calculated automatically.
    + allowed_spendings: 5 (number, required) - hint on your spendings, helping you to keep in expected_amount. change_amount is calculated automatically as a `expected_amount/number of days in Budget term`. May be recalculated during your actual Budget execution. Only valid is BudgetEntry.even_distribution is set to `True`. If 'BudgetEntry.proration' is set to `False` it will recalculate with each submited budget related transaction as (expected_amount-actual_amount)/number of days *left* in Budget term, negative value will be cut to zero. If `BudgetEntry.proration` is set to `True` it will recalculate with each submited budget related transaction as (expected_amount/number of days in Budget term)*number of days *passed* in Budget term - actual_amount`, negative value will be cut to zero.
    + spending_percent: 2 (number, required) - ratio of spent/planned amounts

### View a BudgetEntry detail [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (BudgetEntry)

### Modify BudgetEntry data [PUT]

+ Request (application/vnd.mdg+json;version=1)
    + Attributes (BudgetEntry)

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes (BudgetEntry)

## BudgetEntry collection [/budgets/{budget_id}/entries?embed={embed}]

+ parameters
    + budget_id: YYYYMMDD (required, string) - ID of owning budget in form of integer
    + embed: currency,category,account (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly

### List budget entries [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + budget_entries (array[BudgetEntry], required) - List of entries of that budget

## Budget entries tree [/budgets/{budget_id}/entries/tree&embed={embed}&filter={filter}]

+ Parameters
    + embed: currency,account (array[string], optional) - Embed actual objects into response. Respective `_id` fields are always filled, but objects are not sent if not requested explicitly. Account objects are not populated with categories in the tree mode.
    + filter: nonzero (enum[string], optional) - Either `nonzero` or `all`. Default is `nonzero`. In `nonzero` mode entries with zero actual spendings and zero expected spendings are not returned, alongside their parent categories. In `all` mode all entries and their categories are always returned.

### Get all Budget entries [GET]

In that mode statistics, similar to budget entry statistics, is calculated for each category. The rules of calculation (prorated/even/one-shot) is
derived from owned entries/sub categories using the following rule: if at least one sub entry is one-shot, all other entries are considered one-show.
If there are no one-show entries, but at least one non-prorated entry, all of them are considered to be even distributed. OTherwise

+ Response 200 (application/vnd.mdg+json;version=1)

        {
            "expense": {
                "entries": [
                    {
                        "id": 291,
                        "account": null,
                        "category": null,
                        "proration": false,
                        "account_id": 2065,
                        "category_id": null,
                        "even_distribution": true,
                        "expected_amount": 100500.00,
                        "actual_amount": 0,
                        "allowed_spendings": 0,
                        "spending_percent": 0
                    }
                ],
                "categories": [
                    {
                        "id": 2,
                        "name": "pets",
                        "expected_amount": 100500.00,
                        "actual_amount": 0,
                        "allowed_spendings": 0,
                        "spending_percent": 0
                        "entries": [
                            {
                                "id": 291,
                                "account": null,
                                "category": null,
                                "proration": false,
                                "account_id": 2065,
                                "category_id": null,
                                "even_distribution": true,
                                "expected_amount": 100500.00,
                                "actual_amount": 0,
                                "allowed_spendings": 0,
                                "spending_percent": 0
                            }
                        ],
                        "categories": {
                            "entries": [],
                            "categories": []
                        }
                    }
            ]
        }

## BudgetEntry duplication ops [/budgets/{budget_id}/entries/copy/{mode}/{source_budget_id}]

+ Parameters
    + budget_id: YYYYMMDD (required, string) - ID of owning budget in form of integer
    + mode: preserve (enum[string], required) - Copying mode, could be `preserve` or `overwrite`. In the `preserve` mode existing entries are preserved, otherwise they will be overwritten. Entries which are set in the target budget, but have zero value in the source budget are untouched.
    + source_budget_id: YYYYMMDD (required, string) - ID of source budget for the operations.

### Copy budget entries [PUT]

+ Response 204
    + Attributes
        + budget_entries (array[BudgetEntry], required) - List of entries of that budget

# Group Report

Various reporting data, mostly read-only

## TotalsReport [/reports/totals]

Provides assets overview information.

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + report (array[TotalsReportEntry], required) - Array of report entries.

## AssetSimpleReport [/reports/assets/simple?startDate={startDate}&endDate={endDate}&granularity={granularity}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.
  + granularity (number, required) - Distance in days between report entries inside of startDate-endDate range. startDate and endDate are always included (if they do not match).



### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.


## AssetCurrencyReport [/reports/assets/currency?startDate={startDate}&endDate={endDate}&granularity={granularity}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.
  + granularity (number, required) - Distance in days between report entries inside of startDate-endDate range. startDate and endDate are always included (if they do not match).

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## AssetTypeReport [/reports/assets/type?startDate={startDate}&endDate={endDate}&granularity={granularity}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.
  + granularity (number, required) - Distance in days between report entries inside of startDate-endDate range. startDate and endDate are always included (if they do not match).

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## IncomeEventsReport [/reports/income/events?startDate={startDate}&endDate={endDate}&granularity={granularity}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.
  + granularity (number, required) - Distance in days between report entries inside of startDate-endDate range. startDate and endDate are always included (if they do not match).

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## ExpenseEventsReport [/report/expense/events?startDate={startDate}&endDate={endDate}&granularity={granularity}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.
  + granularity (number, required) - Distance in days between report entries inside of startDate-endDate range. startDate and endDate are always included (if they do not match).

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## IncomeStructureReport [/report/income/accounts?startDate={startDate}&endDate={endDate}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## ExpenseStructureReport [/report/expense/accounts?startDate={startDate}&endDate={endDate}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format.

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + series (array[ReportSeries], required) - Array of datapoints series.

## BudgetExecutionReport [/report/budget/execution?startDate={startDate}&endDate={endDate}]

+ Parameters
  + startDate: `YYYY-MM-DD` (string, required) - First day of report in YYYY-MM-DD format. It will include budget, that may have been started earlier, then that date, but have ended after it.
  + endDate: `YYYY-MM-DD` (string, required) - Last day of report in YYYY-MM-DD format. And vice versa, budget, that have been finished after that date, but it's beginning is earlier, will be included.

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + actual_income (array[number], required) - Array of actual income values for each date
        + actual_expense (array[number], required) - Array of actual expense values for each date
        + expected_income (array[number], required) - Array of expected income values for each date
        + expected_expense (array[number], required) - Array of expected expense values for each date
        + profit (array[number], required) - Array of profit values for each date

## BudgetCashflowReport [/report/budget/cashflow/{budgetid}]

+ Parameters
  + budgetid: `YYYYMMDD` (string, required) - Budget id to use as a report data source.

### View a report [GET]

+ Response 200 (application/vnd.mdg+json;version=1)
    + Attributes
        + dates (array[string], required) - Array of reported dates in format YYYY-MM-DD
        + actual (array[ReportSeries], required) - Array of actual cumulative balances per day on all operational accounts
        + expected (array[ReportSeries], required) - Array of expected cumulative balances per day on all operational accounts. Expected transactions are calculated with respected to scheduled budget entries and budget daily allowed spendings.

# Data Structures

## Problem (object)
+ title: 'Requested currency could not be found' (string, required) - Human-friendly error description
+ status: 404 (number, required) - HTTP Status code, must match response status code
+ instance: /currency/1 (string, optional) - URL of errored object if applicable
+ detail: 'We can not find currency with specified code in the database, check its id please.' (string, optional) - More

## Operation (object)

Single operation in a transation.

+ Attributes
    + account_id: 1 (number, required) - Related account id
    + amount: 7.40 (number, required) - account balance change
    + rate: 0.04 (number, optional) - exchange rate to be applied

## BudgetEntryMode (enum)

+ SINGLE - Transactions for that entry should happen occasionally (or even once) during the budget period. For example 'rent' is usually occasional, as you pay it only once during dudget period.
+ EVEN - Transactions for that entry happen evenly during the budget period. For example, 'meal budget' is usually evenly distributed, you spent it in small pieces almost every day during dudget period.
+ PRORATED - Same as 'EVEN', marks that transactions  for that entry happen evenly during the budget period. But instead of evenly allowing to spend same amount every day, in that mode a cumulative total is tracked. For example in case of allocating 30 units to some entry in a monthly budget and not spending it, in the even mode allowed spending will be 30/15=2 for any day left. But in the prorated mode it will be 15 for the 15th day and still 1 for remaining days

## BudgetPair (object)

Budget specific thing. As budget manages a predicted future and harsh reality at the same time, we usually operation with a pair of number, one is actual and another one is expected. This data structure is used for that

+ Attributes
    + actual: 1000 (number, required) - Amount that actually was reached during budget execution
    + expected: 2000 (number, required) - Amount that planned to be reached during budget execution

## ReportSeriesEntry

A single entry of report series. Names of the fields are based on [Highcharts API requirements](https://api.highcharts.com/highcharts/series.area.data.y):

+ Attributes
    + y: 0.06(number, required) - A single datapoint. In case it is a monetary value, it will be converted to the primary currency.
    + custom: 120 (number, required) - Original monetary value in the original currency. Should be ignored for non-monetary values.

## ReportSeries

Report series represent a single data-series for reporting, consists of a series name, datapoints array and recommended chart type

+ Attributes
    + name: 'CZK' (string, required) - Series name
    + data: [1,2,3] (array[number], required) - Series datapoints. Array should have exactly same amount of datapoints as reports `dates` array has.
    + type: 'area' (string, required) - Recommended type of chart. Consult https://api.highcharts.com/highcharts/series for list of valid char types.

## Amount

Amount holds a pair of a some balance amoutn and related currency code. Only code is used there, as reports are provided only for rendering, not editing.

+ Attributes
    + amount (number, required) - Balance amount value.
    + name (string, optional) - Related entry name, such as currency, category etc
    + date: `YYYY-MM-DD` (string, required) - Date for which entry is valid

## TotalsReportEntry

Data structure for a single totals report entry, linked to a specific asset type.

+ Attributes
    + category_name: Cash (string, required) - Asset category name.
    + primary_balance: 100500 (number, required) - Sum of all the asset account of specified asset type, converted to a primary currency
    + amounts (array[Amount, required) - Detailed report of totals of the specified asset type, grouped by currency. Entry value is a sum of all asset account of parent's asset type and same currency.
