name: MDG CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.46.0'
          sourcePath: 'backend/src/main/java'
          analyzeModifiedFilesOnly: 'false'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: Fail build if there a PMD violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
      - name: Run spotbugs checks
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots clean compile spotbugs:check
      - name: Build with Maven
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots clean package spring-boot:repackage
